In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

# Import, Clean, Standarize the Data

In [2]:
#Import and drop unncessary column(s)
hair_data_df = pd.read_csv("Resources\Predict_Hair_Fall.csv").drop('Id', axis = 1 )
hair_data_df.columns = hair_data_df.columns.str.strip()
hair_data_df.head()

Genetics Hormonal Changes Medical Conditions Medications & Treatments  \
0      Yes               No            No Data                  No Data   
1       No               No             Eczema              Antibiotics   
2       No               No         Dermatosis         Antifungal Cream   
3      Yes              Yes           Ringworm              Antibiotics   
4       No               No          Psoriasis                 Accutane   

  Nutritional Deficiencies    Stress  Age Poor Hair Care Habits  \
0     Magnesium deficiency  Moderate   19                   Yes   
1     Magnesium deficiency      High   43                   Yes   
2       Protein deficiency  Moderate   26                   Yes   
3       Biotin Deficiency   Moderate   46                   Yes   
4          Iron deficiency  Moderate   30                    No   

  Environmental Factors Smoking Weight Loss  Hair Loss  
0                   Yes      No          No          0  
1                   Yes      No          No          0  
2                   Yes      No         Yes          0  
3                   Yes      No          No          0  
4                   Yes     Yes          No          1

In [3]:
# Create get_dummies
hair_data_dummies = pd.get_dummies(hair_data_df)
hair_data_dummies.head()

Age  Hair Loss  Genetics_No  Genetics_Yes  Hormonal Changes_No  \
0   19          0        False          True                 True   
1   43          0         True         False                 True   
2   26          0         True         False                 True   
3   46          0        False          True                False   
4   30          1         True         False                 True   

   Hormonal Changes_Yes  Medical Conditions_Alopecia Areata   \
0                 False                                False   
1                 False                                False   
2                 False                                False   
3                  True                                False   
4                 False                                False   

   Medical Conditions_Androgenetic Alopecia  Medical Conditions_Dermatitis  \
0                                     False                          False   
1                                     False                          False   
2                                     False                          False   
3                                     False                          False   
4                                     False                          False   

   Medical Conditions_Dermatosis  ...  Stress_Low  Stress_Moderate  \
0                          False  ...       False             True   
1                          False  ...       False            False   
2                           True  ...       False             True   
3                          False  ...       False             True   
4                          False  ...       False             True   

   Poor Hair Care Habits_No  Poor Hair Care Habits_Yes  \
0                     False                       True   
1                     False                       True   
2                     False                       True   
3                     False                       True   
4                      True                      False   

   Environmental Factors_No  Environmental Factors_Yes  Smoking_No  \
0                     False                       True        True   
1                     False                       True        True   
2                     False                       True        True   
3                     False                       True        True   
4                     False                       True       False   

   Smoking_Yes  Weight Loss_No  Weight Loss_Yes  
0        False            True            False  
1        False            True            False  
2        False           False             True  
3        False            True            False  
4         True            True            False  

[5 rows x 50 columns]

In [ ]:
# Export clean data
# hair_data_df.to_csv("Predict_Hair_Fall_Clean.csv", index = False)

In [4]:
# Assign X and y variables
y = hair_data_df['Hair Loss'].ravel()
X = hair_data_dummies.drop('Hair Loss', axis = 1)



C:\Users\johns\AppData\Local\Temp\ipykernel_2088\3254197979.py:2: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  y = hair_data_df['Hair Loss'].ravel()


In [5]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [6]:
#Intialize scaler
X_scaler = MinMaxScaler() #Explain why minmax and not standard

#Fitting the scaler
X_scaler = X_scaler.fit(X_train)

#Fit scaler on training set and testing set
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [7]:
# Build Random Forest Model
rf_model = RandomForestClassifier(n_estimators=500, random_state=78)

rf_model = rf_model.fit(X_train, y_train)

prediction = rf_model.predict(X_test)

## Model Evaluation

In [8]:
# Display Model Evaluation
cm = confusion_matrix(y_test, prediction)
print("Confusion Matrix")
print(cm)

print("Classification Report")
print(classification_report(y_test, prediction))

Confusion Matrix
[[72 55]
 [58 65]]
Classification Report
              precision    recall  f1-score   support

           0       0.55      0.57      0.56       127
           1       0.54      0.53      0.53       123

    accuracy                           0.55       250
   macro avg       0.55      0.55      0.55       250
weighted avg       0.55      0.55      0.55       250



In [9]:
# Build Random Forest Model
rf_model = RandomForestClassifier(n_estimators=500, random_state=78)

rf_model = rf_model.fit(X_train, y_train)

prediction = rf_model.predict(X_train)

In [10]:
# Display Model Evaluation
cm = confusion_matrix(y_train, prediction)
print("Confusion Matrix")
print(cm)

print("Classification Report")
print(classification_report(y_train, prediction))

Confusion Matrix
[[375   0]
 [  0 374]]
Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       375
           1       1.00      1.00      1.00       374

    accuracy                           1.00       749
   macro avg       1.00      1.00      1.00       749
weighted avg       1.00      1.00      1.00       749



Model Evaluation Notes:
- The model is overfitting predictions on the training dataset is 100% for balding vs not balding . . .whereas predictions on the test set for balding and balding is . . .

- optimize model remove multicorr and reduce number for n_components. . . PCA was worse so remove PCA

# Optimizing the Model

In [11]:
hair_data_dummies_2 = pd.get_dummies(hair_data_df, drop_first=True) # Useful when preventing multicollinearity in regression models.
hair_data_dummies_2.head()

Age  Hair Loss  Genetics_Yes  Hormonal Changes_Yes  \
0   19          0          True                 False   
1   43          0         False                 False   
2   26          0         False                 False   
3   46          0          True                  True   
4   30          1         False                 False   

   Medical Conditions_Androgenetic Alopecia  Medical Conditions_Dermatitis  \
0                                     False                          False   
1                                     False                          False   
2                                     False                          False   
3                                     False                          False   
4                                     False                          False   

   Medical Conditions_Dermatosis  Medical Conditions_Eczema  \
0                          False                      False   
1                          False                       True   
2                           True                      False   
3                          False                      False   
4                          False                      False   

   Medical Conditions_No Data  Medical Conditions_Psoriasis  ...  \
0                        True                         False  ...   
1                       False                         False  ...   
2                       False                         False  ...   
3                       False                         False  ...   
4                       False                          True  ...   

   Nutritional Deficiencies_Vitamin A Deficiency  \
0                                          False   
1                                          False   
2                                          False   
3                                          False   
4                                          False   

   Nutritional Deficiencies_Vitamin D Deficiency  \
0                                          False   
1                                          False   
2                                          False   
3                                          False   
4                                          False   

   Nutritional Deficiencies_Vitamin E deficiency  \
0                                          False   
1                                          False   
2                                          False   
3                                          False   
4                                          False   

   Nutritional Deficiencies_Zinc Deficiency  Stress_Low  Stress_Moderate  \
0                                     False       False             True   
1                                     False       False            False   
2                                     False       False             True   
3                                     False       False             True   
4                                     False       False             True   

   Poor Hair Care Habits_Yes  Environmental Factors_Yes  Smoking_Yes  \
0                       True                       True        False   
1                       True                       True        False   
2                       True                       True        False   
3                       True                       True        False   
4                      False                       True         True   

   Weight Loss_Yes  
0            False  
1            False  
2             True  
3            False  
4            False  

[5 rows x 40 columns]

In [12]:
y = hair_data_df['Hair Loss'].ravel()
X = hair_data_dummies_2.drop('Hair Loss', axis = 1)

C:\Users\johns\AppData\Local\Temp\ipykernel_2088\949536360.py:1: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  y = hair_data_df['Hair Loss'].ravel()


In [13]:
# Splitting into Train and Test sets
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X, y, random_state=78)

In [14]:
#Intialize scaler
X_scaler = MinMaxScaler() # Scale the data to a specific range and when the data does not contain outliers

#Fitting the scaler
X_scaler = X_scaler.fit(X_train_2)

#Fit scaler on training set and testing set
X_train_scaled_2 = X_scaler.transform(X_train_2)
X_test_scaled_2 = X_scaler.transform(X_test_2)

In [15]:
# Build Random Forest Model
rf_model = RandomForestClassifier(n_estimators=150, random_state=78) #Lowering number of n_estimators

rf_model = rf_model.fit(X_train_2, y_train_2)

prediction = rf_model.predict(X_test_2)

In [16]:
# Display Model Evaluation
cm = confusion_matrix(y_test_2, prediction)
print("Confusion Matrix")
print(cm)

print("Classification Report")
print(classification_report(y_test_2, prediction))

Confusion Matrix
[[76 51]
 [55 68]]
Classification Report
              precision    recall  f1-score   support

           0       0.58      0.60      0.59       127
           1       0.57      0.55      0.56       123

    accuracy                           0.58       250
   macro avg       0.58      0.58      0.58       250
weighted avg       0.58      0.58      0.58       250

